### ISSUE TITLE
Pynequa: Implement 2nd set of Search Endpoints

### ISSUE THREAD

**Issue by anisbhsl** [NASA-IMPACT/pynequa#11]
Implement all remaining `search.*` endpoint methods and fix tests.

The endpoints include: 

- search.alerts
- search.baskets
-  search.labels
-  search.savedQueries
-  search.suggest
-  search.custom
-  suggestField
-  engine.sql
```[tasklist]
### Tasks
- [ ] Implement endpoint methods
- [x] Update README
- [x] Update tests
- [ ] Create a new release (0.2.0)
- [ ] Verify if docs have been updated or not
```
