### ISSUE TITLE
PI Milestone: Open source python-sinequa library #161

### ISSUE THREAD

**Issue by anisbhsl** [NASA-IMPACT/pynequa#3]
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/sinequa_py/issues/1
- [ ] https://github.com/NASA-IMPACT/sinequa_py/issues/4
- [ ] https://github.com/NASA-IMPACT/sinequa_py/issues/5
- [x] Pynequa: Release to pypi
```

**Comment by anisbhsl** [comment]
Package is officially release to pypi https://pypi.org/project/pynequa/
