### ISSUE TITLE
Pynequa: Add auto build and test scripts

### ISSUE THREAD

**Issue by anisbhsl** [NASA-IMPACT/pynequa#5]
## Description

Add github workflows to perform build on new push to develop/master branch. Include tests files. 

### Acceptance Criteria:

- [ ] Github build script
- [ ] Unit tests for implemented methods

```[tasklist]
### Tasks
- [x] Add github build script
- [ ] Add first set of unit tests
```
